DROP TABLE IF EXISTS `players`;
CREATE TABLE `players` (
  `id` int(11) NOT NULL,
  `steam_id` varchar(17) NOT NULL,
  `name` varchar(64) DEFAULT NULL,
  `veterancy` varchar(32) DEFAULT NULL,
  `character` varchar(128) DEFAULT NULL,
  `heal_points` int(11) NOT NULL DEFAULT 0,
  `weld_points` int(11) NOT NULL DEFAULT 0,
  `headshots` int(11) NOT NULL DEFAULT 0,
  `shotgun_damage` int(11) NOT NULL DEFAULT 0,
  `bullpup_damage` int(11) NOT NULL DEFAULT 0,
  `melee_damage` int(11) NOT NULL DEFAULT 0,
  `fire_damage` int(11) NOT NULL DEFAULT 0,
  `explosive_damage` int(11) NOT NULL DEFAULT 0,
  `wins` int(11) NOT NULL DEFAULT 0,
  `losts` int(11) NOT NULL DEFAULT 0,
  `map_score` bigint(20) unsigned NOT NULL,
  `online_time` int(11) NOT NULL DEFAULT 0,
  `total_kills` int(11) NOT NULL DEFAULT 0,
  `waves_total` bigint(20) unsigned NOT NULL,
  `team_kills` int(11) NOT NULL DEFAULT 0,
  `stalker_kills` int(11) NOT NULL DEFAULT 0,
  `scrake_kills` int(11) NOT NULL DEFAULT 0,
  `fleshpound_kills` int(11) NOT NULL DEFAULT 0,
  `patriarch_kills_main` int(10) unsigned NOT NULL,
  `patriarch_kills_weak` int(10) unsigned NOT NULL,
  `miniboss_kills` int(10) unsigned NOT NULL,
  `account_key` varchar(255) DEFAULT NULL,
  `last_map` varchar(64) DEFAULT NULL,
  `reg_ip` varchar(16) DEFAULT NULL,
  `last_ip` varchar(16) DEFAULT NULL,
  `first_visit` varchar(32) DEFAULT NULL,
  `last_visit` varchar(32) DEFAULT NULL,
  `first_enter` tinyint(1) NOT NULL DEFAULT 1,
  `last_win_date` varchar(32) DEFAULT NULL,
  `last_win_map` varchar(64) DEFAULT NULL,
  `prestige` tinyint(1) NOT NULL,
  `clan_id` int(10) unsigned DEFAULT NULL,
  `clan_name` varchar(32) DEFAULT NULL,
  `clan_abbr` varchar(4) DEFAULT NULL,
  `clan_icon` varchar(128) DEFAULT NULL,
  `clan_leader` tinyint(1) unsigned NOT NULL DEFAULT 0,
  `clan_join_date` varchar(32) DEFAULT NULL,
  `clan_zombie_kills` bigint(20) unsigned NOT NULL DEFAULT 0,
  `clan_patriarch_kills` bigint(20) unsigned NOT NULL DEFAULT 0,
  `title_text` varchar(32) DEFAULT NULL,
  `inventory` varchar(256) DEFAULT NULL,
  `lang` int(1) NOT NULL DEFAULT 0,
  `gunslinger_damage` int(11) NOT NULL DEFAULT 0,
  `premium_type` tinyint(1) NOT NULL DEFAULT -1,
  `premium_expiration_date` varchar(32) DEFAULT NULL,
  `inactive` tinyint(1) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
